[[- if eq .Values.provider.kind "cloud-director" ]]
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-policies-ux-background-controller
  labels:
    rbac.kyverno.io/aggregate-to-background-controller: "true"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "list", "update", "delete"]
[[- end ]]
