[[- if eq .Values.provider.flavor "capi" ]]
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cluster-names
  annotations:
    policies.kyverno.io/title: Restrict names of Clusters
    policies.kyverno.io/subject: Clusters
    policies.kyverno.io/description: >-
      Cluster names must not be longer than 20 characters.
spec:
  validationFailureAction: Enforce
  rules:
  - name: cluster-name-maximum-length
    match:
      any:
      - resources:
          kinds:
          - cluster.x-k8s.io/v1beta1/Cluster
    validate:
      message: "cluster name must be no longer than 20 characters"
      deny:
        conditions:
          any:
          - key: "{{ length('{{request.object.metadata.name}}') }}"
            operator: GreaterThan
            value: 20

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-machine-pool-names
  annotations:
    policies.kyverno.io/title: Restrict names of MachinePools
    policies.kyverno.io/subject: MachinePools
    policies.kyverno.io/description: >-
      MachinePool names are of the form {CLUSTER_NAME}-{MD_NAME},
      therefore their total length must not exceed 31 (20 for CLUSTER_NAME
      and 10 for MACHINE_POOL_NAME).
spec:
  validationFailureAction: Enforce
  rules:
  - name: machine-pool-name-maximum-length
    match:
      any:
      - resources:
          kinds:
          - MachinePool
    validate:
      message: "machine pool name must not be longer than 31 characters (20 for cluster name, 1 for '-', 10 for user defined named)"
      deny:
        conditions:
          any:
          - key: "{{ length('{{request.object.metadata.name}}') }}"
            operator: GreaterThan
            value: 31

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: machine-deployment-names
  annotations:
    policies.kyverno.io/title: Restrict names of MachineDeployments
    policies.kyverno.io/subject: MachineDeployments
    policies.kyverno.io/description: >-
      MachineDeployment names are of the form {CLUSTER_NAME}-{MD_NAME},
      therefore their total length must not exceed 31 (20 for CLUSTER_NAME
      and 10 for MACHINE_DEPLOYMENT_NAME).
spec:
  validationFailureAction: Enforce
  rules:
  - name: machine-deployment-name-maximum-length
    match:
      any:
      - resources:
          kinds:
          - MachineDeployment
    validate:
      message: "machine deployment name must not be longer than 31 characters (20 for cluster name, 1 for '-', 10 for user defined named)"
      deny:
        conditions:
          any:
          - key: "{{ length('{{request.object.metadata.name}}') }}"
            operator: GreaterThan
            value: 31
[[- end]]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
  name: kyverno:gs-ux:cluster-names
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
  name: kyverno:gs-ux:machine-deployment-names
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
  name: kyverno:gs-ux:restrict-machine-pool-names
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinepools
  verbs:
  - get
  - list
  - watch
