apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-policies-ux-admission-controller
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
rules:
  - apiGroups:
    - cluster.x-k8s.io
    - infrastructure.cluster.x-k8s.io
    - infrastructure.giantswarm.io
    resources:
    - awsclusters
    - awscontrolplanes
    - awsmachinedeployments
    - azureclusters
    - azuremachinepools
    - clusters
    - vcdclusters
    - vsphereclusters
    - kubeadmcontrolplanes
    - machinedeployments
    - machinepools
    verbs: ["get", "list"]
  - apiGroups: ["application.giantswarm.io"]
    resources: ["apps"]
    verbs: ["get", "list"]
  - apiGroups: ["security.giantswarm.io"]
    resources: ["organizations"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "namespaces"]
    verbs: ["get", "list"]
