apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-resource-deletion-if-has-prevent-deletion-label
  annotations:
    policies.kyverno.io/title: Block resource deletion if the resource has the `giantswarm.io/prevent-deletion` label.
    policies.kyverno.io/subject: "*"
    policies.kyverno.io/description: >-
      We want to block the deletion of resources that have the
      `giantswarm.io/prevent-deletion` label.

      The `giantswarm.io/prevent-deletion` label, together with this policy, is used as a
      mechanism to prevent accidental deletion of important resources.
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: block-resource-deletion-if-has-prevent-deletion-label
    match:
      any:
      - resources:
          kinds:
[[- range .Values.preventDeletionLabelPolicy.resources ]]
  [[- $resource := . -]]
  [[- range $.Capabilities.APIVersions ]]
    [[- if eq (last (splitList "/" .)) $resource ]]
          - [[ $resource ]]
    [[- end ]]
  [[- end ]]
[[- end ]]
    # Needed for resources that have duplicated names across different apiGroups, eg: cluster.postgresql.org/v1/Cluster and cluster.x-k8s.io/v1beta2/Cluster
[[- range .Values.preventDeletionLabelPolicy.gvk ]]
          - [[ . ]]
[[- end ]]
          selector:
            matchLabels:
              giantswarm.io/prevent-deletion: "*"
    validate:
      message: "Remove the `giantswarm.io/prevent-deletion` label from this resource before deleting it."
      deny:
        conditions:
        - key: "{{request.operation}}"
          operator: AnyIn
          value:
          - DELETE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
    rbac.kyverno.io/aggregate-to-reports-controller: "true"
  name: kyverno:gs-ux:block-resource-deletion-if-has-prevent-deletion-label
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.giantswarm.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - machinedeployments
  - machinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kubeadmcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.giantswarm.io
  resources:
  - organizations
  verbs:
  - get
  - list
  - watch
